<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
//  use App\Http\Controllers\PublicApiController;



 use App\Http\Controllers\LocationController;
 use App\Http\Controllers\AuthController;
 use App\Http\Controllers\CategoriesController;
 use App\Http\Controllers\ApiController;
 use App\Http\Controllers\BankAccountController;
 use App\Http\Controllers\BookingController;
 use App\Http\Controllers\ProviderDetailController;
 use App\Http\Controllers\HandymanController;
 use App\Http\Controllers\DocumentController;
 use App\Http\Controllers\TestingController;
 
 
Route::post('signup', [ApiController::class, 'signup']);
Route::post('login', [ApiController::class, 'login']);
Route::get('countries', [LocationController::class, 'getCountries']);
Route::post('states', [LocationController::class, 'getStates']);
Route::post('serviceslist', [LocationController::class, 'serviceslist']);
Route::get('cities/{stateId}', [LocationController::class, 'getCities']);
Route::get('profile/{user}', [ApiController::class, 'show']);
Route::get('faqs_list', [ApiController::class, 'faqs_list']);
Route::get('commission_list', [ApiController::class, 'commission_list']);
Route::post('profile_update', [ApiController::class, 'profile_update']);
Route::post('cashfree_gateway', [ApiController::class, 'cashfree_gateway']);
Route::post('available_status', [ApiController::class, 'available_status']);
Route::post('verify_id', [ApiController::class, 'verify_id']);
Route::post('add_bank', [ApiController::class, 'add_bank']);
Route::post('bankupdate', [ApiController::class, 'bankupdate']);
Route::post('ifsc', [ApiController::class, 'ifsc']);
Route::post('addon_update', [ApiController::class, 'addon_update']);
Route::post('services_update', [ApiController::class, 'services_update']);
Route::get('coupons_list', [ApiController::class, 'coupons_list']);
Route::post('houseman_list', [CategoriesController::class, 'houseman_list']);
Route::post('provider_list', [CategoriesController::class, 'provider_list']);
Route::post('houseman_online', [CategoriesController::class, 'houseman_online']);
Route::any('categories/subcategories', [CategoriesController::class, 'categories']);
Route::post('categories_delete', [CategoriesController::class, 'categories_delete']);
Route::get('subcategories/{categoryId}', [CategoriesController::class, 'subcategory']);
Route::get('service/{categoryId}/{subcategoryId}/{userId}', [CategoriesController::class, 'services']);
Route::Post('address_servics', [ApiController::class, 'address_servics']);
Route::post('/slots_list', [ApiController::class, 'slots_list']);
Route::get('bookings_status', [ApiController::class, 'bookings_status']);
Route::Post('addon_view', [ApiController::class, 'addon_view']);
Route::Post('settings', [ApiController::class, 'settings']);
Route::Post('filter_by', [ApiController::class, 'filter_by']);
Route::post('add_categories', [ApiController::class, 'add_categories']);
Route::post('add_sub_categories', [ApiController::class, 'add_sub_categories']);
Route::Post('bookings_view', [ApiController::class, 'bookings_view']);
Route::Post('bookings_houseman_view', [ApiController::class, 'bookings_houseman_view']);
Route::post('bookingshistory', [ApiController::class, 'bookingshistory']);
Route::post('booking_cancel', [ApiController::class, 'booking_cancel']);
Route::post('address_users', [ApiController::class, 'address_users']);
Route::Post('verifyid_view', [ApiController::class, 'verifyid_view']);
Route::post('categories_view', [ApiController::class, 'categories_view']);
Route::Post('change_password', [ApiController::class, 'Change_password']);
Route::post('subcategories_view', [ApiController::class, 'subcategories_view']);
Route::Post('verifyid_delete', [ApiController::class, 'verifyid_delete']);
Route::Post('service_view', [ApiController::class, 'service_view']);
Route::Post('provider_handy_doc', [ApiController::class, 'provider_handy_doc']);
Route::Post('help_support_view', [ApiController::class, 'help_support_view']);
Route::Post('service_view_users', [ApiController::class, 'service_view_users']);
Route::get('service_random', [ApiController::class, 'service_random']);
Route::Post('service_view_filter', [ApiController::class, 'service_view_filter']);
Route::Post('address_delete', [ApiController::class, 'address_delete']);
Route::Post('services_delete', [ApiController::class, 'services_delete']);
Route::Post('account_delete', [ApiController::class, 'account_delete']);
Route::Post('banklist', [ApiController::class, 'banklist']);
Route::Post('subcategories_delete', [CategoriesController::class, 'subcategories_delete']);
Route::Post('verify_id_update', [ApiController::class, 'verify_id_update']);
Route::Post('addon_delete', [ApiController::class, 'addon_delete']);
Route::Post('address_view', [ApiController::class, 'address_view']);
Route::Post('address_on_off', [ApiController::class, 'address_on_off']);
Route::Post('address_update', [ApiController::class, 'address_update']);
Route::Post('address_default', [ApiController::class, 'address_default']);
Route::any('sliders', [ApiController::class, 'Slider_view']);
Route::get('duration_view', [ApiController::class, 'duration_view']);
Route::post('provideo_view', [ApiController::class, 'provideo_view']);
Route::Post('/teamlist', [ApiController::class, 'teamlist']);
Route::Post('/reviews_list_handyman', [ApiController::class, 'reviews_list_handyman']);
Route::get('zone_Management', [ApiController::class, 'zone_Management']);
Route::get('housman_view', [ApiController::class, 'housman_view']);
Route::get('language_view', [ApiController::class, 'language_view']);
Route::any('policy_all', [ApiController::class, 'policy']);
Route::get('refundpolicy', [ApiController::class, 'refund_policy']);
Route::post('monthly_revenue', [ApiController::class, 'monthly_revenue']);
Route::get('aboutapp', [ApiController::class, 'about_app']);
Route::get('termcondition', [ApiController::class, 'term_condition']);
Route::get('helpsupport', [ApiController::class, 'help_support']);
Route::post('/bank_accounts_add', [BankAccountController::class, 'store']);
Route::post('/services_add', [ApiController::class, 'services_add']);
Route::post('/services_book', [ApiController::class, 'services_book']);
Route::post('/help_desk_add', [ApiController::class, 'help_desk_add']);
Route::post('/reviews_add', [ApiController::class, 'reviews_add']);
Route::post('/slots_add', [ApiController::class, 'slots_add']);
Route::post('/reviews_update', [ApiController::class, 'reviews_update']);
Route::post('/addon_service_add', [ApiController::class, 'addon_service_add']);
Route::post('/shops_add', [ApiController::class, 'shops_add']);
Route::get('/bank_account_get/{user}', [BankAccountController::class, 'show']);
Route::post('/packages_add', [ApiController::class, 'packages_add']);
Route::post('/bank_account_update', [BankAccountController::class, 'update']);
Route::get('/bank_account_delete/{id}', [BankAccountController::class, 'destroy_details']);
Route::post('categories_update', [ApiController::class, 'categories_update']);
Route::post('subcategories_update', [ApiController::class, 'subcategories_update']);
Route::post('services_view', [ApiController::class, 'services_view']);
Route::post('packages_view', [ApiController::class, 'packages_view']);
Route::post('packages_list', [ApiController::class, 'packages_list']);
Route::post('packages_delete', [ApiController::class, 'packages_delete']);
Route::post('pricring_delete', [ApiController::class, 'pricring_delete']);
Route::get('blog', [ApiController::class, 'blog']);
Route::post('/bookings', [BookingController::class, 'paidbooking']);
Route::post('work', [LocationController::class, 'work']);
Route::get('/work_delete/{id}', [LocationController::class, 'destroy_work']);
Route::get('/view_work/{userid}', [LocationController::class, 'view_work']);
Route::get('/wallet/{user_id}', [LocationController::class, 'showWalletAmount']);
Route::get('/wallet_history/{user_id}', [LocationController::class, 'walletHistory']);
Route::post('/favorites', [LocationController::class, 'Favorite']);
Route::get('/favorites/{user_id}', [LocationController::class, 'showFavorite']);
Route::get('/delfavorites/{user_id}/{service_id}', [LocationController::class, 'removeFavorite']);
Route::get('get_blogs', [ApiController::class, 'getblogs']);
Route::get('/remove_blogs/{id}', [ApiController::class, 'removeblogs']);
Route::get('/reviewslist/{user_id}', [ApiController::class, 'reviewslist']);
Route::get('/shopslist/{providers_id}', [ApiController::class, 'shopslist']);
Route::Post('bookings_details', [ApiController::class, 'bookings_details']);
Route::Post('services_details', [ApiController::class, 'services_details']);
Route::Post('shops_details', [ApiController::class, 'shops_details']);
Route::get('/home_provider/{provider_id}', [ApiController::class, 'home_provider']);
Route::get('/home_houseman/{houseman_id}', [ApiController::class, 'home_houseman']);
Route::post('/slotslist', [ApiController::class, 'slotslist']);
Route::get('/reviews_delete/{id}', [ApiController::class, 'reviews_delete']);
Route::get('/shops_delete/{id}', [ApiController::class, 'shops_delete']);
Route::post('/slotslistProviders', [ApiController::class, 'slotslistProviders']);
Route::post('/Favorite_provideo', [ApiController::class, 'Favorite_provideo']);
Route::get('/show_bookings/{userId}', [BookingController::class, 'showBooking']);
Route::post('/store_blog', [ApiController::class, 'storeblog']);
Route::post('/register', [ProviderDetailController::class, 'register']);
Route::post('/sign_in', [ProviderDetailController::class, 'sign_in']);
Route::get('/service/count/{provider_id}', [ProviderDetailController::class, 'getServiceCount']);
Route::get('/booking/count/{provider_id}', [ProviderDetailController::class, 'getbookingCount']);
Route::get('/providers', [ProviderDetailController::class, 'getProviders']);
Route::post('model_update', [ProviderDetailController::class, 'model_update']);
Route::post('/pricing_add', [ApiController::class, 'pricing_add']);
Route::get('/Pricing_view', [ApiController::class, 'Pricing_view']);
Route::get('handyman_profile/{user}', [ProviderDetailController::class, 'show']);
Route::get('handymans', [ProviderDetailController::class, 'getHandymans']);
Route::post('handyman_update', [ApiController::class, 'handyman_update']);
Route::post('handyman_on_off', [ApiController::class, 'handyman_on_off']);
Route::post('/providerservice', [ProviderDetailController::class, 'providerservice']);
Route::get('final_bookings/{providerId}', [ProviderDetailController::class,'final_Booking']);
Route::post('accept_booking', [ProviderDetailController::class, 'acceptBooking']);
Route::post('decline_Booking', [ProviderDetailController::class, 'declineBooking']);
Route::post('assign_Handyman', [ProviderDetailController::class, 'assignHandyman']);
Route::post('/store_service', [ProviderDetailController::class, 'storeservice']);
Route::get('/remove_service/{id}', [ProviderDetailController::class, 'removeservice']);
Route::post('service_update', [ProviderDetailController::class, 'serviceupdate']);
Route::post('shopupdate', [ProviderDetailController::class, 'shopupdate']);
Route::post('packageupdate', [ProviderDetailController::class, 'packageupdate']);
Route::post('handyman_register', [ProviderDetailController::class, 'handyregister']);
Route::get('/term_condition_handy', [HandymanController::class, 'term_condition_handy']);
Route::get('/privacy_policy_handy', [HandymanController::class, 'privacy_policy']);
Route::get('/help_support_handy', [HandymanController::class, 'help_support']);
Route::get('/my_provider/{userId}', [HandymanController::class, 'showProviderDetails']);
Route::get('/handyman_booking/{handymanId}', [HandymanController::class, 'handymanbooking']);
Route::get('/notification/{houseman_id}', [HandymanController::class, 'notification']);
Route::post('/accept_handyman_booking', [HandymanController::class, 'accepthandymanBooking']);
Route::get('documents_types', [DocumentController::class, 'getDocumentTypes']);
Route::get('documents/{userId}', [DocumentController::class, 'listDocuments']);
Route::post('documents_add', [DocumentController::class, 'addDocument']);
Route::post('/payin', [BookingController::class, 'payin']);
Route::get('/check_payment', [BookingController::class, 'checkPayment']);
Route::post('/wallet_recharge', [BookingController::class, 'walletrecharge']);
Route::get('/wallet_payment/{transactionId}', [BookingController::class, 'walletcheckPayment']);

Route::get('recharge_history/{userId}', [BookingController::class,'rechargehistory']);

Route::get('/search', [CategoriesController::class, 'search']);
Route::get('services', [CategoriesController::class, 'getServices']);
Route::get('destroy_services/{id}', [CategoriesController::class, 'destroy_services']);


Route::post('test', [TestingController::class, 'test']);
Route::get('/check_paymentt', [TestingController::class, 'checkPaymentt']);


Route::post('/create-order', [TestingController::class, 'createOrder']);
Route::get('/order-list/all', [BookingController::class, 'Orderlist']);
Route::get('/order-details-by-id/{id}', [BookingController::class, 'Orderdetailsid']);

Route::get('/dashboard', [DashboardController::class, 'dashboard'])->name('dashboard');            
Route::get('/item', [CategoryController::class, 'index'])->name('item');
Route::get('/subitem', [CategoryController::class, 'subcategorys'])->name('subitem');
Route::get('/services', [CategoryController::class, 'services'])->name('services');
Route::get('/users', [DashboardController::class, 'users'])->name('users');
Route::get('/users_one/{id}', [DashboardController::class, 'users_one'])->name('users_one');
Route::get('/reviews', [DashboardController::class, 'reviews'])->name('reviews');
Route::get('/transaction_details', [DashboardController::class, 'transaction_details'])->name('transaction_details');